### ISSUE TITLE
Twitter API not working

### ISSUE THREAD

**Issue by aemxn** [aimanbaharum/shitstorm-twitter#3]
```
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/shitstorm-twitter/twitteroauth.php:195
Stack trace:
#0 /var/www/html/shitstorm-twitter/twitteroauth.php(182): TwitterOAuth->http('https://api.twi...', 'GET')
#1 /var/www/html/shitstorm-twitter/twitteroauth.php(142): TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
#2 /var/www/html/shitstorm-twitter/index.php(41): TwitterOAuth->get('search/tweets', Array)
#3 {main}
  thrown in /var/www/html/shitstorm-twitter/twitteroauth.php on line 195
```

Fixed.

Cause: curl is not installed in ubuntu 16.04 php7.0

**Comment by aemxn** [comment]
```
PHP Notice:  Undefined property: stdClass::$statuses in /var/www/html/shitstorm-twitter/index.php on line 43
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/shitstorm-twitter/index.php on line 43
```

**Comment by aemxn** [comment]
Fixed

Cause: Token expired
